#alias ls='colorls -G' #OpenBSD
#alias ls='ls -G' #FreeBSD
alias less='/usr/share/vim/vim*/macros/less.sh'
alias o='popd'
alias p='pushd $PWD'
alias rm='rm -f'
alias vi='vim'
#alias psql='sudo -u postgres -i psql'
#alias virsh='virsh -c qemu:///system'
