syntax enable
set nocompatible
set tabstop=8
set softtabstop=4
set shiftwidth=4
set mouse=
set vb t_vb=
set t_Co=256
set bg=dark
set display=lastline
set complete+=k
set completeopt+=fuzzy
set clipboard+=unnamed

" vim swap file directory
set directory^=$HOME/.vim/swap//

"disable formatting when pasting
set pastetoggle=<F2>

map <silent> <F3> :call StripTrailing()<CR> " strip trailing whitespace
map <silent> <F6> :call ToggleHex()<CR> " Hex Editor
map <silent> <F7> :setlocal spell! spell?<CR>
map <silent> <F9> :runtime! syntax/2html.vim<CR> " export to html

" Turn on the WiLd menu
set wildmenu

"Always show current position
set ruler

" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch

" Don't redraw while executing macros (good performance config)
set lazyredraw

" For regular expressions turn magic on
set magic

" Show matching brackets when text indicator is over them
set showmatch
set mat=5

" How many tenths of a second to blink when matching brackets
set mat=2

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines

set matchpairs+=<:>

let html_use_css=1 " export to html should use CSS

filetype plugin on
filetype indent on

" Always show the status line
set laststatus=2

set statusline=
set statusline +=%1*\ %n\ %*            "buffer number
set statusline +=%5*%{&ff}%*            "file format
set statusline +=%3*%y%*                "file type
set statusline +=%4*\ %<%F%*            "full path
set statusline +=%2*%m%*                "modified flag
set statusline +=%1*%=%5l%*             "current line
set statusline +=%2*/%L%*               "total lines
set statusline +=%1*%4v\ %*             "virtual column number
set statusline +=%2*0x%04B\ %*          "character under cursor

augroup custom
    autocmd!
    autocmd BufNewFile,BufRead Makefile.* set filetype=make
    autocmd BufNewFile,BufRead *.py set expandtab
    autocmd FileType python set omnifunc=python3complete#Complete
    autocmd BufWritePre * call StripTrailing()
    autocmd BufNewFile,BufRead *.rsc set syntax=rsc
    autocmd FileType yaml setlocal ai ts=2 sts=2 sw=2 expandtab
augroup END
